import React from 'react'
import { useDeleteStudentMutation, useGetStudentsQuery } from '../Services/api'
import { Vortex } from 'react-loader-spinner';
import styles from '../table.module.css'
import { toast } from 'react-toastify'
import { Link } from 'react-router-dom';
const ViewStudent = () => {
  const { data, isLoading, error, isSuccess } = useGetStudentsQuery(); //custom hooks generated by RTK Query automatically...
  const [delStudent] = useDeleteStudentMutation(); //custom hooks generated by RTK Query automatically...

  const handleDelete = (id) => {
    delStudent(id);
    toast.error(`student having id: ${id} has been removed from student table`, {
      theme: 'colored'
    });
  }
  return (
    <>
      <table className={`${styles.tableContainer} table`}>
        <thead>
          <tr>
            <th scope="col">id</th>
            <th scope="col">Name</th>
            <th scope="col">Age</th>
            <th scope="col">Gender</th>
            <th scope="col">Marks</th>
            <th scope='col'></th>
            <th scope='col'></th>
          </tr>
        </thead>
        <tbody>
          {
            (isLoading) ? <>
              <div className='text-center' style={{ margin: '20px auto' }}>
                <Vortex
                  visible={true}
                  height="80"
                  width="80"
                  ariaLabel="vortex-loading"
                  wrapperStyle={{}}
                  wrapperClass="vortex-wrapper"
                  colors={['red', 'green', 'blue', 'yellow', 'orange', 'purple']}
                />
              </div>
            </> : <>
              {
                (data?.length === 0) ? <>
                  <tr colspan={10} className='text-center'>
                      <td className='text-danger'><h4>No record Found</h4></td>
                  </tr>
                </> : <>
                  {
                    isSuccess && data && data?.map(item => {
                      return (<>
                        <tr>
                          <td>{item?.id}</td>
                          <td>{item?.name}</td>
                          <td>{item?.age}</td>
                          <td>{item?.gender}</td>
                          <td>{item?.marks}</td>
                          <td><Link className='btn btn-outline-success' to={`/editStudent/${item?.id}`}>Edit</Link></td>
                          <td><button className='btn btn-outline-danger' onClick={() => handleDelete(item?.id)}>Delete</button></td>
                        </tr>
                      </>)
                    })
                  }
                </>
              }
            </>
          }
        </tbody>
      </table>

    </>
  )
}

export default ViewStudent